/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/webhooks/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Telegram Webhook */
        post: operations["telegram_webhook_api_webhooks_telegram_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Requests */
        get: operations["list_requests_api_requests_get"];
        put?: never;
        /** Create Request */
        post: operations["create_request_api_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Request */
        get: operations["get_request_api_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Request */
        patch: operations["update_request_api_requests__request_id__patch"];
        trace?: never;
    };
    "/api/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clients */
        get: operations["list_clients_api_clients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Client */
        get: operations["get_client_api_clients__client_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_api_dashboard_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Services */
        get: operations["list_services_api_services_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings Status */
        get: operations["get_settings_status_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIAnalysisOut */
        AIAnalysisOut: {
            /** Id */
            id: number;
            intent: components["schemas"]["Intent"];
            /** Confidence */
            confidence: number;
            /** Service Name */
            service_name?: string | null;
            /** Preferred Date */
            preferred_date?: string | null;
            /** Preferred Time */
            preferred_time?: string | null;
            /** Requires Manual Review */
            requires_manual_review: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ClientDetailOut */
        ClientDetailOut: {
            client: components["schemas"]["ClientOut"];
            /** Requests */
            requests?: components["schemas"]["RequestOut"][];
        };
        /** ClientOut */
        ClientOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            /** Telegram User Id */
            telegram_user_id?: number | null;
            /** Notes */
            notes?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DashboardStatsOut */
        DashboardStatsOut: {
            /** Total */
            total: number;
            status_counts: components["schemas"]["StatusCountsOut"];
            /** Requires Review */
            requires_review: number;
            /** By Day */
            by_day?: components["schemas"]["DayCountOut"][];
            /** By Source */
            by_source?: components["schemas"]["SourceCountOut"][];
            /** Top Services */
            top_services?: components["schemas"]["ServiceCountOut"][];
            /** Recent Requests */
            recent_requests?: components["schemas"]["RequestOut"][];
        };
        /** DayCountOut */
        DayCountOut: {
            /** Date */
            date: string;
            /** Count */
            count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Intent
         * @enum {string}
         */
        Intent: "booking" | "question" | "complaint" | "price_request" | "cancel_booking" | "reschedule" | "other";
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MessageDirection
         * @enum {string}
         */
        MessageDirection: "in" | "out";
        /** MessageOut */
        MessageOut: {
            /** Id */
            id: number;
            direction: components["schemas"]["MessageDirection"];
            source: components["schemas"]["MessageSource"];
            /** Text */
            text: string;
            /** Telegram Update Id */
            telegram_update_id?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * MessageSource
         * @enum {string}
         */
        MessageSource: "telegram" | "web" | "manual";
        /** RegisterIn */
        RegisterIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name: string;
            /** Business Name */
            business_name: string;
        };
        /** RequestCreateIn */
        RequestCreateIn: {
            /** Client Id */
            client_id: number;
            /** Text */
            text: string;
        };
        /** RequestDetailOut */
        RequestDetailOut: {
            /** Id */
            id: number;
            /** Client Id */
            client_id: number;
            client?: components["schemas"]["ClientOut"] | null;
            /** Service Id */
            service_id?: number | null;
            /** Service Name */
            service_name?: string | null;
            status: components["schemas"]["RequestStatus"];
            source: components["schemas"]["MessageSource"];
            /** Summary */
            summary?: string | null;
            /** Preferred Date */
            preferred_date?: string | null;
            /** Preferred Time */
            preferred_time?: string | null;
            /** Requires Manual Review */
            requires_manual_review: boolean;
            /** Created By User Id */
            created_by_user_id?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            latest_ai?: components["schemas"]["AIAnalysisOut"] | null;
            /** Messages */
            messages?: components["schemas"]["MessageOut"][];
            /** Ai Analyses */
            ai_analyses?: components["schemas"]["AIAnalysisOut"][];
            /** Status History */
            status_history?: components["schemas"]["StatusHistoryOut"][];
        };
        /** RequestOut */
        RequestOut: {
            /** Id */
            id: number;
            /** Client Id */
            client_id: number;
            client?: components["schemas"]["ClientOut"] | null;
            /** Service Id */
            service_id?: number | null;
            /** Service Name */
            service_name?: string | null;
            status: components["schemas"]["RequestStatus"];
            source: components["schemas"]["MessageSource"];
            /** Summary */
            summary?: string | null;
            /** Preferred Date */
            preferred_date?: string | null;
            /** Preferred Time */
            preferred_time?: string | null;
            /** Requires Manual Review */
            requires_manual_review: boolean;
            /** Created By User Id */
            created_by_user_id?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            latest_ai?: components["schemas"]["AIAnalysisOut"] | null;
        };
        /**
         * RequestStatus
         * @enum {string}
         */
        RequestStatus: "NEW" | "IN_PROGRESS" | "CONFIRMED" | "COMPLETED" | "CANCELLED";
        /** RequestUpdateIn */
        RequestUpdateIn: {
            status?: components["schemas"]["RequestStatus"] | null;
            /** Service Id */
            service_id?: number | null;
            /** Preferred Date */
            preferred_date?: string | null;
            /** Preferred Time */
            preferred_time?: string | null;
            /** Summary */
            summary?: string | null;
            /** Requires Manual Review */
            requires_manual_review?: boolean | null;
        };
        /** ServiceCountOut */
        ServiceCountOut: {
            /** Service Name */
            service_name: string;
            /** Count */
            count: number;
        };
        /** ServiceOut */
        ServiceOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /** Price */
            price?: number | null;
            /** Is Active */
            is_active: boolean;
        };
        /** SettingsOut */
        SettingsOut: {
            /** Ai Provider */
            ai_provider: string;
            /** Ai Mode */
            ai_mode: string;
            /** Ai Key Set */
            ai_key_set: boolean;
            /** Telegram Bot Token Set */
            telegram_bot_token_set: boolean;
            /** Telegram Webhook Secret Set */
            telegram_webhook_secret_set: boolean;
        };
        /** SourceCountOut */
        SourceCountOut: {
            source: components["schemas"]["MessageSource"];
            /** Count */
            count: number;
        };
        /** StatusCountsOut */
        StatusCountsOut: {
            /**
             * New
             * @default 0
             */
            new: number;
            /**
             * In Progress
             * @default 0
             */
            in_progress: number;
            /**
             * Confirmed
             * @default 0
             */
            confirmed: number;
            /**
             * Completed
             * @default 0
             */
            completed: number;
            /**
             * Cancelled
             * @default 0
             */
            cancelled: number;
        };
        /** StatusHistoryOut */
        StatusHistoryOut: {
            /** Id */
            id: number;
            old_status?: components["schemas"]["RequestStatus"] | null;
            new_status: components["schemas"]["RequestStatus"];
            /** Changed By User Id */
            changed_by_user_id?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TelegramMessageIn */
        TelegramMessageIn: {
            /** Message Id */
            message_id: number;
            from: components["schemas"]["TelegramUserIn"];
            /** Text */
            text: string;
        };
        /** TelegramUserIn */
        TelegramUserIn: {
            /** Id */
            id: number;
            /**
             * First Name
             * @default
             */
            first_name: string;
            /**
             * Last Name
             * @default
             */
            last_name: string;
            /**
             * Username
             * @default
             */
            username: string;
        };
        /** TelegramWebhookIn */
        TelegramWebhookIn: {
            /** Update Id */
            update_id: number;
            message?: components["schemas"]["TelegramMessageIn"] | null;
        };
        /** TokenOut */
        TokenOut: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserOut"];
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            role: components["schemas"]["UserRole"];
            /** Business Id */
            business_id: number;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "admin" | "manager";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    telegram_webhook_api_webhooks_telegram_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramWebhookIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_requests_api_requests_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["RequestStatus"] | null;
                requires_review?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_request_api_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_request_api_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_request_api_requests__request_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clients_api_clients_get: {
        parameters: {
            query?: {
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_api_clients__client_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_api_dashboard_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStatsOut"];
                };
            };
        };
    };
    list_services_api_services_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceOut"][];
                };
            };
        };
    };
    get_settings_status_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
