"""initial schema

Revision ID: eff9494455f0
Revises: 
Create Date: 2026-09-25 23:23:57.764203

"""
from alembic import op
import sqlalchemy as sa


revision = 'eff9494455f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'telegram_user_id', name='uq_clients_business_telegram')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_business_id'), ['business_id'], unique=False)

    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_business_id'), ['business_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', name='user_role', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_business_id'), ['business_id'], unique=False)

    op.create_table('client_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='request_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('source', sa.Enum('telegram', 'web', 'manual', name='request_source', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('preferred_date', sa.String(length=100), nullable=True),
    sa.Column('preferred_time', sa.String(length=100), nullable=True),
    sa.Column('requires_manual_review', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_requests_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_requests_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_requests_status'), ['status'], unique=False)

    op.create_table('ai_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('intent', sa.Enum('booking', 'question', 'complaint', 'price_request', 'cancel_booking', 'reschedule', 'other', name='ai_intent', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('service_name', sa.String(length=200), nullable=True),
    sa.Column('preferred_date', sa.String(length=100), nullable=True),
    sa.Column('preferred_time', sa.String(length=100), nullable=True),
    sa.Column('requires_manual_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['client_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_analyses_request_id'), ['request_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.Enum('in', 'out', name='message_direction', native_enum=False, create_constraint=True, length=10), nullable=False),
    sa.Column('source', sa.Enum('telegram', 'web', 'manual', name='message_source', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('telegram_update_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['client_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'telegram_update_id', name='uq_messages_business_telegram_update')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_request_id'), ['request_id'], unique=False)

    op.create_table('request_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.Enum('NEW', 'IN_PROGRESS', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='old_request_status', native_enum=False, create_constraint=True, length=20), nullable=True),
    sa.Column('new_status', sa.Enum('NEW', 'IN_PROGRESS', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='request_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['client_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_status_history_request_id'), ['request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_status_history_request_id'))

    op.drop_table('request_status_history')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_request_id'))
        batch_op.drop_index(batch_op.f('ix_messages_client_id'))
        batch_op.drop_index(batch_op.f('ix_messages_business_id'))

    op.drop_table('messages')
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_analyses_request_id'))

    op.drop_table('ai_analyses')
    with op.batch_alter_table('client_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_requests_status'))
        batch_op.drop_index(batch_op.f('ix_client_requests_client_id'))
        batch_op.drop_index(batch_op.f('ix_client_requests_business_id'))

    op.drop_table('client_requests')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_business_id'))

    op.drop_table('users')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_business_id'))

    op.drop_table('services')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_business_id'))

    op.drop_table('clients')
    op.drop_table('businesses')
    # ### end Alembic commands ###
